/* eslint-disable */
// Auto-generated by generate-referentiel-ts.js
// Full article data with body content — used ONLY for article detail pages.
// For listings and cards, use @/data/referentiel-meta (much lighter, no body content).

import type { ReferentielArticleMeta } from "./referentiel-meta";
import { CATEGORY_LABELS } from "./referentiel-meta";
export { CATEGORY_LABELS };
import a1 from "../content/referentiel/comment-obtenir-la-certification-qualiopi.json";
import a2 from "../content/referentiel/comment-obtenir-la-certification-qualiopi.en.json";
import a3 from "../content/referentiel/comment-creer-un-cfa-en-france-en-2026.json";
import a4 from "../content/referentiel/comment-creer-un-cfa-en-france-en-2026.en.json";
import a5 from "../content/referentiel/comment-financer-une-formation-professionnelle-sans-reste-a-charge.json";
import a6 from "../content/referentiel/comment-financer-une-formation-professionnelle-sans-reste-a-charge.en.json";
import a7 from "../content/referentiel/comment-creer-un-programme-de-formation-conforme-qualiopi.json";
import a8 from "../content/referentiel/comment-creer-un-programme-de-formation-conforme-qualiopi.en.json";
import a9 from "../content/referentiel/comment-declarer-son-activite-de-formation-professionnelle.json";
import a10 from "../content/referentiel/comment-declarer-son-activite-de-formation-professionnelle.en.json";
import a11 from "../content/referentiel/comment-concevoir-un-bilan-de-competences-conforme.json";
import a12 from "../content/referentiel/comment-concevoir-un-bilan-de-competences-conforme.en.json";
import a13 from "../content/referentiel/comment-monter-un-dossier-de-certification-rncp.json";
import a14 from "../content/referentiel/comment-monter-un-dossier-de-certification-rncp.en.json";
import a15 from "../content/referentiel/comment-calculer-le-cout-pedagogique-dune-formation.json";
import a16 from "../content/referentiel/comment-calculer-le-cout-pedagogique-dune-formation.en.json";
import a17 from "../content/referentiel/comment-gerer-les-alternants-droits-obligations-encadrement.json";
import a18 from "../content/referentiel/comment-gerer-les-alternants-droits-obligations-encadrement.en.json";
import a19 from "../content/referentiel/comment-evaluer-les-acquis-des-apprenants-de-facon-valide.json";
import a20 from "../content/referentiel/comment-evaluer-les-acquis-des-apprenants-de-facon-valide.en.json";
import a21 from "../content/referentiel/comment-construire-un-referentiel-de-formation-de-a-a-z.json";
import a22 from "../content/referentiel/comment-construire-un-referentiel-de-formation-de-a-a-z.en.json";
import a23 from "../content/referentiel/comment-attirer-des-apprentis-et-des-stagiaires-en-2026.json";
import a24 from "../content/referentiel/comment-attirer-des-apprentis-et-des-stagiaires-en-2026.en.json";
import a25 from "../content/referentiel/comment-obtenir-et-utiliser-les-fonds-de-la-taxe-d-apprentissage.json";
import a26 from "../content/referentiel/comment-obtenir-et-utiliser-les-fonds-de-la-taxe-d-apprentissage.en.json";
import a27 from "../content/referentiel/comment-digitaliser-ses-formations-sans-perdre-la-qualite-pedagogique.json";
import a28 from "../content/referentiel/comment-digitaliser-ses-formations-sans-perdre-la-qualite-pedagogique.en.json";
import a29 from "../content/referentiel/comment-gerer-la-relation-avec-les-opco-au-quotidien.json";
import a30 from "../content/referentiel/comment-gerer-la-relation-avec-les-opco-au-quotidien.en.json";
import a31 from "../content/referentiel/comment-rediger-une-convention-de-formation-conforme-a-la-loi.json";
import a32 from "../content/referentiel/comment-rediger-une-convention-de-formation-conforme-a-la-loi.en.json";
import a33 from "../content/referentiel/comment-construire-un-plan-de-developpement-des-competences-pour-une-entreprise-cliente.json";
import a34 from "../content/referentiel/comment-construire-un-plan-de-developpement-des-competences-pour-une-entreprise-cliente.en.json";
import a35 from "../content/referentiel/comment-creer-une-formation-eligible-au-cpf.json";
import a36 from "../content/referentiel/comment-creer-une-formation-eligible-au-cpf.en.json";
import a37 from "../content/referentiel/comment-piloter-la-qualite-pedagogique-de-ses-formateurs.json";
import a38 from "../content/referentiel/comment-piloter-la-qualite-pedagogique-de-ses-formateurs.en.json";
import a39 from "../content/referentiel/comment-gerer-la-sous-traitance-de-formation-legalement.json";
import a40 from "../content/referentiel/comment-gerer-la-sous-traitance-de-formation-legalement.en.json";
import a41 from "../content/referentiel/comment-obtenir-des-certifications-de-qualite-au-dela-de-qualiopi.json";
import a42 from "../content/referentiel/comment-obtenir-des-certifications-de-qualite-au-dela-de-qualiopi.en.json";
import a43 from "../content/referentiel/comment-developper-une-activite-de-formation-en-entreprise-intra.json";
import a44 from "../content/referentiel/comment-developper-une-activite-de-formation-en-entreprise-intra.en.json";
import a45 from "../content/referentiel/comment-accompagner-les-apprenants-en-situation-de-handicap-psh.json";
import a46 from "../content/referentiel/comment-accompagner-les-apprenants-en-situation-de-handicap-psh.en.json";
import a47 from "../content/referentiel/comment-faire-une-veille-reglementaire-efficace-sur-la-formation-professionnelle.json";
import a48 from "../content/referentiel/comment-faire-une-veille-reglementaire-efficace-sur-la-formation-professionnelle.en.json";
import a49 from "../content/referentiel/comment-mesurer-le-retour-sur-investissement-d-une-formation.json";
import a50 from "../content/referentiel/comment-mesurer-le-retour-sur-investissement-d-une-formation.en.json";
import a51 from "../content/referentiel/comment-acceder-aux-appels-d-offres-publics-pour-la-formation.json";
import a52 from "../content/referentiel/comment-acceder-aux-appels-d-offres-publics-pour-la-formation.en.json";
import a53 from "../content/referentiel/comment-construire-une-offre-de-vae.json";
import a54 from "../content/referentiel/comment-construire-une-offre-de-vae.en.json";
import a55 from "../content/referentiel/comment-gerer-les-evaluations-a-froid-et-prouver-l-impact-pedagogique.json";
import a56 from "../content/referentiel/comment-gerer-les-evaluations-a-froid-et-prouver-l-impact-pedagogique.en.json";
import a57 from "../content/referentiel/comment-preparer-et-reussir-un-audit-de-renouvellement-qualiopi.json";
import a58 from "../content/referentiel/comment-preparer-et-reussir-un-audit-de-renouvellement-qualiopi.en.json";
import a59 from "../content/referentiel/comment-developper-une-offre-de-formation-a-l-international.json";
import a60 from "../content/referentiel/comment-developper-une-offre-de-formation-a-l-international.en.json";
import a61 from "../content/referentiel/comment-financer-la-formation-de-mes-salaries-sans-tout-payer-moi-meme.json";
import a62 from "../content/referentiel/comment-financer-la-formation-de-mes-salaries-sans-tout-payer-moi-meme.en.json";
import a63 from "../content/referentiel/comment-construire-un-plan-de-developpement-des-competences-efficace.json";
import a64 from "../content/referentiel/comment-construire-un-plan-de-developpement-des-competences-efficace.en.json";
import a65 from "../content/referentiel/comment-choisir-un-organisme-de-formation-serieux-pour-mon-entreprise.json";
import a66 from "../content/referentiel/comment-choisir-un-organisme-de-formation-serieux-pour-mon-entreprise.en.json";
import a67 from "../content/referentiel/comment-mettre-en-place-une-politique-de-formation-dans-ma-pme.json";
import a68 from "../content/referentiel/comment-mettre-en-place-une-politique-de-formation-dans-ma-pme.en.json";
import a69 from "../content/referentiel/comment-gerer-les-entretiens-professionnels-obligatoires-tous-les-2-ans.json";
import a70 from "../content/referentiel/comment-gerer-les-entretiens-professionnels-obligatoires-tous-les-2-ans.en.json";
import a71 from "../content/referentiel/comment-utiliser-le-cpf-de-mes-salaries-pour-financer-des-formations-utiles-a-l-entreprise.json";
import a72 from "../content/referentiel/comment-utiliser-le-cpf-de-mes-salaries-pour-financer-des-formations-utiles-a-l-entreprise.en.json";
import a73 from "../content/referentiel/comment-former-mes-managers-rapidement-et-avec-impact.json";
import a74 from "../content/referentiel/comment-former-mes-managers-rapidement-et-avec-impact.en.json";
import a75 from "../content/referentiel/comment-mesurer-l-efficacite-d-une-formation-achetee-a-un-prestataire-externe.json";
import a76 from "../content/referentiel/comment-mesurer-l-efficacite-d-une-formation-achetee-a-un-prestataire-externe.en.json";
import a77 from "../content/referentiel/comment-former-mes-equipes-a-l-intelligence-artificielle-concretement.json";
import a78 from "../content/referentiel/comment-former-mes-equipes-a-l-intelligence-artificielle-concretement.en.json";
import a79 from "../content/referentiel/comment-financer-une-reconversion-professionnelle-pour-un-salarie.json";
import a80 from "../content/referentiel/comment-financer-une-reconversion-professionnelle-pour-un-salarie.en.json";
import a81 from "../content/referentiel/comment-identifier-les-competences-manquantes-dans-mon-entreprise.json";
import a82 from "../content/referentiel/comment-identifier-les-competences-manquantes-dans-mon-entreprise.en.json";
import a83 from "../content/referentiel/comment-mettre-en-place-le-tutorat-interne-comme-outil-de-formation.json";
import a84 from "../content/referentiel/comment-mettre-en-place-le-tutorat-interne-comme-outil-de-formation.en.json";
import a85 from "../content/referentiel/comment-former-mes-commerciaux-de-facon-continue-et-mesurable.json";
import a86 from "../content/referentiel/comment-former-mes-commerciaux-de-facon-continue-et-mesurable.en.json";
import a87 from "../content/referentiel/comment-accompagner-un-salarie-vers-une-vae.json";
import a88 from "../content/referentiel/comment-accompagner-un-salarie-vers-une-vae.en.json";
import a89 from "../content/referentiel/comment-organiser-une-action-de-formation-en-interne-formateur-interne.json";
import a90 from "../content/referentiel/comment-organiser-une-action-de-formation-en-interne-formateur-interne.en.json";
import a91 from "../content/referentiel/comment-aborder-la-formation-lors-d-un-accord-gpec-ou-d-une-restructuration.json";
import a92 from "../content/referentiel/comment-aborder-la-formation-lors-d-un-accord-gpec-ou-d-une-restructuration.en.json";
import a93 from "../content/referentiel/comment-calculer-le-budget-formation-optimal-pour-mon-entreprise.json";
import a94 from "../content/referentiel/comment-calculer-le-budget-formation-optimal-pour-mon-entreprise.en.json";
import a95 from "../content/referentiel/comment-former-des-salaries-en-teletravail-de-facon-engageante.json";
import a96 from "../content/referentiel/comment-former-des-salaries-en-teletravail-de-facon-engageante.en.json";
import a97 from "../content/referentiel/comment-gerer-les-refus-de-formation-d-un-salarie.json";
import a98 from "../content/referentiel/comment-gerer-les-refus-de-formation-d-un-salarie.en.json";
import a99 from "../content/referentiel/comment-prouver-que-mon-entreprise-respecte-ses-obligations-en-matiere-de-formation.json";
import a100 from "../content/referentiel/comment-prouver-que-mon-entreprise-respecte-ses-obligations-en-matiere-de-formation.en.json";
import a101 from "../content/referentiel/comment-integrer-la-formation-dans-l-onboarding-de-nouveaux-collaborateurs.json";
import a102 from "../content/referentiel/comment-integrer-la-formation-dans-l-onboarding-de-nouveaux-collaborateurs.en.json";
import a103 from "../content/referentiel/comment-developper-une-culture-de-l-apprentissage-continu-dans-mon-entreprise.json";
import a104 from "../content/referentiel/comment-developper-une-culture-de-l-apprentissage-continu-dans-mon-entreprise.en.json";
import a105 from "../content/referentiel/comment-choisir-entre-une-formation-presentielle-distancielle-ou-hybride.json";
import a106 from "../content/referentiel/comment-choisir-entre-une-formation-presentielle-distancielle-ou-hybride.en.json";
import a107 from "../content/referentiel/comment-former-mes-equipes-sur-les-sujets-de-compliance-et-de-reglementation.json";
import a108 from "../content/referentiel/comment-former-mes-equipes-sur-les-sujets-de-compliance-et-de-reglementation.en.json";
import a109 from "../content/referentiel/comment-financer-la-formation-d-un-salarie-qui-veut-changer-de-metier-en-restant-dans-l-entreprise.json";
import a110 from "../content/referentiel/comment-financer-la-formation-d-un-salarie-qui-veut-changer-de-metier-en-restant-dans-l-entreprise.en.json";
import a111 from "../content/referentiel/comment-choisir-entre-former-en-interne-ou-externaliser-la-formation.json";
import a112 from "../content/referentiel/comment-choisir-entre-former-en-interne-ou-externaliser-la-formation.en.json";
import a113 from "../content/referentiel/comment-piloter-la-formation-dans-un-groupe-multi-sites-ou-international.json";
import a114 from "../content/referentiel/comment-piloter-la-formation-dans-un-groupe-multi-sites-ou-international.en.json";
import a115 from "../content/referentiel/comment-utiliser-la-formation-pour-fideliser-les-talents-et-reduire-le-turnover.json";
import a116 from "../content/referentiel/comment-utiliser-la-formation-pour-fideliser-les-talents-et-reduire-le-turnover.en.json";
import a117 from "../content/referentiel/comment-repondre-a-une-obligation-de-formation-sectorielle-specifique.json";
import a118 from "../content/referentiel/comment-repondre-a-une-obligation-de-formation-sectorielle-specifique.en.json";
import a119 from "../content/referentiel/comment-negocier-un-accord-de-formation-avec-les-representants-du-personnel.json";
import a120 from "../content/referentiel/comment-negocier-un-accord-de-formation-avec-les-representants-du-personnel.en.json";
import a121 from "../content/referentiel/quel-lms-choisir-pour-mon-organisme-de-formation-ou-mon-entreprise.json";
import a122 from "../content/referentiel/quel-lms-choisir-pour-mon-organisme-de-formation-ou-mon-entreprise.en.json";
import a123 from "../content/referentiel/comment-creer-des-contenus-e-learning-rapidement-et-a-moindre-cout.json";
import a124 from "../content/referentiel/comment-creer-des-contenus-e-learning-rapidement-et-a-moindre-cout.en.json";
import a125 from "../content/referentiel/comment-l-intelligence-artificielle-transforme-la-formation-professionnelle.json";
import a126 from "../content/referentiel/comment-l-intelligence-artificielle-transforme-la-formation-professionnelle.en.json";
import a127 from "../content/referentiel/quelles-sont-les-meilleures-plateformes-e-learning-et-comment-les-comparer.json";
import a128 from "../content/referentiel/quelles-sont-les-meilleures-plateformes-e-learning-et-comment-les-comparer.en.json";
import a129 from "../content/referentiel/quel-outil-de-classe-virtuelle-choisir-pour-la-formation-synchrone.json";
import a130 from "../content/referentiel/quel-outil-de-classe-virtuelle-choisir-pour-la-formation-synchrone.en.json";
import a131 from "../content/referentiel/comment-ameliorer-le-taux-de-completion-de-mes-formations-en-ligne.json";
import a132 from "../content/referentiel/comment-ameliorer-le-taux-de-completion-de-mes-formations-en-ligne.en.json";
import a133 from "../content/referentiel/qu-est-ce-que-le-microlearning-et-quand-l-utiliser.json";
import a134 from "../content/referentiel/qu-est-ce-que-le-microlearning-et-quand-l-utiliser.en.json";
import a135 from "../content/referentiel/comment-utiliser-la-gamification-pour-rendre-la-formation-plus-efficace.json";
import a136 from "../content/referentiel/comment-utiliser-la-gamification-pour-rendre-la-formation-plus-efficace.en.json";
import a137 from "../content/referentiel/quel-outil-de-gestion-de-la-formation-choisir-tms-sirh-formation.json";
import a138 from "../content/referentiel/quel-outil-de-gestion-de-la-formation-choisir-tms-sirh-formation.en.json";
import a139 from "../content/referentiel/comment-produire-des-videos-pedagogiques-sans-gros-budget.json";
import a140 from "../content/referentiel/comment-produire-des-videos-pedagogiques-sans-gros-budget.en.json";
import a141 from "../content/referentiel/comment-personnaliser-les-parcours-de-formation-grace-aux-donnees.json";
import a142 from "../content/referentiel/comment-personnaliser-les-parcours-de-formation-grace-aux-donnees.en.json";
import a143 from "../content/referentiel/comment-utiliser-un-chatbot-ou-un-assistant-ia-en-formation.json";
import a144 from "../content/referentiel/comment-utiliser-un-chatbot-ou-un-assistant-ia-en-formation.en.json";
import a145 from "../content/referentiel/comment-rendre-une-plateforme-de-formation-accessible-aux-personnes-en-situation-de-handicap.json";
import a146 from "../content/referentiel/comment-rendre-une-plateforme-de-formation-accessible-aux-personnes-en-situation-de-handicap.en.json";
import a147 from "../content/referentiel/quelles-sont-les-normes-techniques-de-l-e-learning-scorm-xapi-cmi5.json";
import a148 from "../content/referentiel/quelles-sont-les-normes-techniques-de-l-e-learning-scorm-xapi-cmi5.en.json";
import a149 from "../content/referentiel/comment-mesurer-l-impact-de-la-formation-grace-au-learning-analytics.json";
import a150 from "../content/referentiel/comment-mesurer-l-impact-de-la-formation-grace-au-learning-analytics.en.json";
import a151 from "../content/referentiel/comment-vendre-des-formations-en-ligne.json";
import a152 from "../content/referentiel/comment-vendre-des-formations-en-ligne.en.json";
import a153 from "../content/referentiel/faut-il-developper-une-application-mobile-de-formation.json";
import a154 from "../content/referentiel/faut-il-developper-une-application-mobile-de-formation.en.json";
import a155 from "../content/referentiel/comment-integrer-une-plateforme-de-formation-a-mon-sirh-existant.json";
import a156 from "../content/referentiel/comment-integrer-une-plateforme-de-formation-a-mon-sirh-existant.en.json";
import a157 from "../content/referentiel/comment-proteger-et-monetiser-mes-contenus-de-formation-contre-le-piratage.json";
import a158 from "../content/referentiel/comment-proteger-et-monetiser-mes-contenus-de-formation-contre-le-piratage.en.json";
import a159 from "../content/referentiel/comment-utiliser-l-ia-generative-pour-creer-des-quiz-et-des-exercices.json";
import a160 from "../content/referentiel/comment-utiliser-l-ia-generative-pour-creer-des-quiz-et-des-exercices.en.json";
import a161 from "../content/referentiel/quelles-sont-les-edtech-francaises-prometteuses-et-comment-les-evaluer.json";
import a162 from "../content/referentiel/quelles-sont-les-edtech-francaises-prometteuses-et-comment-les-evaluer.en.json";
import a163 from "../content/referentiel/comment-mettre-en-place-une-strategie-de-blended-learning-reussie.json";
import a164 from "../content/referentiel/comment-mettre-en-place-une-strategie-de-blended-learning-reussie.en.json";
import a165 from "../content/referentiel/quand-la-realite-virtuelle-vr-est-elle-pertinente-en-formation.json";
import a166 from "../content/referentiel/quand-la-realite-virtuelle-vr-est-elle-pertinente-en-formation.en.json";
import a167 from "../content/referentiel/comment-exploiter-les-donnees-de-mon-lms-pour-ameliorer-mes-formations.json";
import a168 from "../content/referentiel/comment-exploiter-les-donnees-de-mon-lms-pour-ameliorer-mes-formations.en.json";
import a169 from "../content/referentiel/comment-migrer-d-un-lms-vers-un-autre-sans-tout-perdre.json";
import a170 from "../content/referentiel/comment-migrer-d-un-lms-vers-un-autre-sans-tout-perdre.en.json";
import a171 from "../content/referentiel/comment-decider-entre-developper-ma-propre-plateforme-ou-en-acheter-une.json";
import a172 from "../content/referentiel/comment-decider-entre-developper-ma-propre-plateforme-ou-en-acheter-une.en.json";
import a173 from "../content/referentiel/comment-integrer-un-catalogue-de-contenus-tiers-dans-mon-dispositif-de-formation.json";
import a174 from "../content/referentiel/comment-integrer-un-catalogue-de-contenus-tiers-dans-mon-dispositif-de-formation.en.json";
import a175 from "../content/referentiel/comment-integrer-un-catalogue-tiers-comme-linkedin-learning-en-entreprise.json";
import a176 from "../content/referentiel/comment-integrer-un-catalogue-tiers-comme-linkedin-learning-en-entreprise.en.json";
import a177 from "../content/referentiel/quand-utiliser-des-outils-no-code-pour-creer-ses-formations.json";
import a178 from "../content/referentiel/quand-utiliser-des-outils-no-code-pour-creer-ses-formations.en.json";
import a179 from "../content/referentiel/comment-preparer-son-organisation-a-l-arrivee-de-l-ia-dans-les-outils-de-formation.json";
import a180 from "../content/referentiel/comment-preparer-son-organisation-a-l-arrivee-de-l-ia-dans-les-outils-de-formation.en.json";

export interface ReferentielArticle extends ReferentielArticleMeta {
  content: string;
}

export const REFERENTIEL: ReferentielArticle[] = [
  a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131, a132, a133, a134, a135, a136, a137, a138, a139, a140, a141, a142, a143, a144, a145, a146, a147, a148, a149, a150, a151, a152, a153, a154, a155, a156, a157, a158, a159, a160, a161, a162, a163, a164, a165, a166, a167, a168, a169, a170, a171, a172, a173, a174, a175, a176, a177, a178, a179, a180,
] as ReferentielArticle[];

export function getReferentielBySlug(slug: string, lang?: string): ReferentielArticle | undefined {
  return REFERENTIEL.find((a) => a.slug === slug && (!lang || a.lang === lang));
}

export function getReferentielSlugs(): string[] {
  return REFERENTIEL.map((a) => a.slug);
}

export function getReferentielByCible(cible: string): ReferentielArticle[] {
  return REFERENTIEL.filter((a) => a.cible === cible);
}

export function getReferentielByThematique(thematique: string): ReferentielArticle[] {
  return REFERENTIEL.filter((a) => a.thematique === thematique);
}
